server:
  port: 9091
spring:
  cloud:
    nacos:
      discovery:
        #      # 命名空间
        namespace: CW_GO
        # 服务注册地址
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://172.16.200.212/insurance?useUnicode=true&characterEncoding=UTF-8
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root